FORMAT: 1A
HOST: https://transprime.org/difftime/api/

# difftime

Difftime is a simple API allowing to retrieve the difference betweeen two 24hour format time
# Example
## Get the time I have spent at work without checking the time sheet :)
###### https://transprime.org/difftime/api/?start=08:30&end=20:00
##Version: 
    Alpha 0.1

## Questions Collection [/?start=[:time]&end=[:time]]

### Get the hour and minute difference [GET]

+ Response 200 (application/json)

    {
        "hour": "11",
        "minute": "30"
    }